# Generated by Django 3.2.3 on 2021-05-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
